service: orgilla-api

frameworkVersion: ">=1.21.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage}
  region: eu-central-1
  memorySize: 256
  timeout: 3

functions:  
  graphql:
    handler: app.server
    events:
    - http:
        path: graphql
        method: post
        cors: true
  playground:
    handler: app.playground
    events:
    - http:
        path: graphql
        method: get
        cors: true